### ISSUE TITLE
Doesn't resize properly on large screens

### ISSUE THREAD

**Issue by pip-install-python** [snehilvj/dmc-docs#125]
![image](https://github.com/user-attachments/assets/23bc3a6f-807c-4d8f-affd-e9f87e0c02e6)

Just noticed this, minor bug but it seems like the dmc docs has a max width, when using dmc docs on full screen with my 32inch monitor the header / side bar started to cut off the content.

**Comment by AnnMarieW** [comment]
Oh, that's weird.  I wonder if it's DMC or the docs app.

Can you please run this app on your huge monitor? https://py.cafe/dash.mantine.components/AppShell-with-all-elements

**Comment by pip-install-python** [comment]
![image](https://github.com/user-attachments/assets/b8602804-7520-49e3-a314-66a41742ac94)

That py.cafe looks good. Not sure why the dmc docs has clipping. Its a very minor bug just thought it was worth mentioning, I'll also tell you the exact width the bug starts happening at in one moment

**Comment by pip-install-python** [comment]
Idk, seems to only be happening on my windows computer, tested the bug on my mac with the larger display and it looks fine 🤷
