### ISSUE TITLE
Tooltip error

### ISSUE THREAD

**Issue by AnnMarieW** [snehilvj/dmc-docs#21]
Hey @snehilvj 
It looks like Tooltip example is crashing the browser. When I run it locally, I see this error, then the browser restarts:

>Uncaught Error: flushSync was called from inside a lifecycle method. It cannot be called when React is already rendering.

**Comment by snehilvj** [comment]
Yeah I came across this too. I upgraded Mantine to 4.2.8 in dmc 0.10.0 and this issue popped up after that. I am downgrading Mantine back for now, but need to investigate this further.
