### ISSUE TITLE
Grid `align=stretch` example not stretched

### ISSUE THREAD

**Issue by nlyle01** [snehilvj/dmc-docs#28]
I haven't dug into the docs code to see if there's a quick fix, but for now just wanted to raise the issue. Comparison below between Mantine and Dash Mantine below:

## [Mantine](https://mantine.dev/core/grid/)
`flex-start` and `stretch`

<img width="862" alt="image" src="https://user-images.githubusercontent.com/50966780/209453449-00731c0f-95bb-418f-8313-afadcc8c67ca.png">

## [Dash Mantine](https://www.dash-mantine-components.com/components/grid)
`flex-start` and `stretch`

<img width="1100" alt="image" src="https://user-images.githubusercontent.com/50966780/209453452-9603d051-e07d-42cb-8db7-23bc68285e09.png">

https://github.com/snehilvj/dmc-docs/blob/main/docs/grid/justify.py#L26
```python
demo = dmc.Grid(
    children=[
        dmc.Col(html.Div("1", style=style), span=3),
        dmc.Col(html.Div("2", style={**style, "minHeight": 80}), span=3),
        dmc.Col(html.Div("3", style={**style, "minHeight": 120}), span=3),
    ],
    gutter="md",
)
```

**Comment by snehilvj** [comment]
Thanks for reporting, it has been fixed.
