### ISSUE TITLE
Question about store data in page

### ISSUE THREAD

**Issue by mito310-kc** [snehilvj/dmc-docs#42]
Hello, 

I'd like to express my appreciation for your Project.
Is it possible to use [dcc.Store](https://dash.plotly.com/dash-core-components/store) to retain data?
I tried modifying the [MultiSelect component](https://github.com/snehilvj/dmc-docs/tree/main/docs/multiselect) from the documentation, but I was unable to retain the data.

**Comment by snehilvj** [comment]
Can you please share an MRE?

**Comment by AnnMarieW** [comment]
Closing due to no MRE
@mito310-kc The dcc.Store component does work with dash-mantine-components.  If this is still an issue, please feel free to ask your question on the [Dash community Forum](https://community.plotly.com/)
