### ISSUE TITLE
Typo in charts docs

### ISSUE THREAD

**Issue by thomktz** [snehilvj/dmc-docs#58]
Hi all, 
Small typo in there: "dnc" -> "dmc"
https://github.com/snehilvj/dmc-docs/blob/c2250d802d864b13a04b3cf7060907e61811930b/docs/chartsintro/chartsintro.md?plain=1#L34

Thanks for the great package!

**Comment by AnnMarieW** [comment]
Hi @thomktz 
Nice catch, thanks.  
Would you like to do a pull request?  If not, no problem, I'll add this to my next update :-)
